# Generated by Django 5.2.4 on 2025-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=100)),
                ("teacher_img", models.ImageField(upload_to="teacher_images/")),
                ("expert_in", models.CharField(max_length=100)),
            ],
        ),
    ]
