# Generated by Django 5.2.4 on 2025-11-07 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addTeachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="upload_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
