# Generated by Django 5.2.4 on 2025-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addTeachers", "0002_teachers_upload_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teachers",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teachers",
            name="twitter_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
