# Generated by Django 5.2.4 on 2025-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("total_course", models.IntegerField()),
                ("subject_img", models.ImageField(upload_to="subject_images/")),
            ],
        ),
    ]
