# Generated by Django 5.2.4 on 2025-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                ("duration", models.DurationField()),
                ("course_name", models.CharField()),
                ("student_enrolled", models.IntegerField()),
                ("course_price", models.IntegerField()),
                ("course_image", models.ImageField(upload_to="courses_images/")),
            ],
        ),
    ]
